resources:
  - url: http://127.0.0.1:5000/rainfall-tracker-card.js
    type: module
views:
  - cards:
      - type: custom:rainfall-tracker-card
        name: Rainfall tracker card Development
        entity: sun.sun
        test_gui: true
